- pytox/core.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/5)
> add lost method group_peernumber_is_ours

- pytox/core.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/6)
> Update to new way of registering the log callback.

- setup.py
- tools/install-deps.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/8)
> Remove a.out after checking whether linking with toxav works.

- Dockerfile
- tools/install-deps.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/13)
> Use https for downloading opus.

- .travis.yml
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/15)
> Support one-big-lib version of toxcore.

- BUILD
- Dockerfile
- Dockerfile-cn
- README.rst
- pytox.ld
- pytox/core.c
- setup.py
- tests/BUILD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/16)
> Merge upstream

- pytox/core.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/18)
> Use tox_options setters instead of the struct members directly.

- BUILD
- pytox/av.c
Introduced in https://github.com/TokTok/c-toxcore/pull/578.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/19)
> Update to split bit_rate_set functions.

- .travis.yml
- Dockerfile
- Dockerfile-cn
- LICENSE.md
Also, build with more Python versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/21)
> Test building pytox with docker on travis.

- README.md
- docs/index.rst
- setup.py
- tools/apicomplete.py
Fixes #25.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/26)
> Prepare for 0.2.0 release.

- examples/echo.py
- examples/phone.py
- pytox/av.c
- pytox/av.h
- pytox/core.c
- pytox/core.h
- pytox/pytox.c
- pytox/util.c
- pytox/util.h
- tests/tests.py
- tools/apicomplete.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/29)
> Update copyright notice.

- .travis.yml
- setup.py
- tests/tests.py
- tools/install-deps.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/31)
> Start measuring test coverage on pytox.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/33)
> Only run coverage on one of the many builds.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/34)
> Add badge of shame for coverage.

- .circleci/config.yml
- pytox/core.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/35)
> Add circleci build using ASAN.

- .travis.yml
- pytox/core.c
- pytox/pytox.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/37)
> Add a clang-analyze job to the travis build.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/42)
> Format yaml files according to yamllint's requirements.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/47)
> Run Travis CI against newer Python versions

- BUILD.bazel
- examples/BUILD.bazel
- pytox/core.c
- pytox/util.c
- pytox/util.h
- tests/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/51)
> Use rules_cc instead of native cc_library rules.

- .gitignore
- setup.py
We'll be releasing as py-toxcore-c there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/55)
> Rename package in preparation for release on PyPi.

- .circleci/config.yml
- .github/settings.yml
- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/61)
> chore: Disable branch builds; only build tags and nightly builds.

- examples/echo.py
- examples/phone.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/58)
> chore: Use a working bootstrap node in pytox examples.

- .cirrus.yml
- .github/settings.yml
- pytox/core.c
This uses toktok-stack and runs pytox tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/py-toxcore-c/66)
> chore: Add cirrus-ci build.

- .circleci/config.yml
- Dockerfile
- tools/gen_api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/py-toxcore-c/84)
> chore: Upgrade to latest cython version (3.0.2).

- BUILD.bazel
- test/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/py-toxcore-c/85)
> chore: Re-enable layering_check now that rules_python supports it.

- Dockerfile
- test/BUILD.bazel
- test/auto_tests/auto_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/py-toxcore-c/114)
> test: Add conference_send_message test.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/py-toxcore-c/119)
> test: Run all tests under asan.

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/py-toxcore-c/120)
> test: Add ubsan to the asan build.

- .circleci/config.yml
- .github/workflows/release.yml
- BUILD.bazel
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/py-toxcore-c/126)
> chore: Add release-drafter github action.

- BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/py-toxcore-c/130)
> chore: Don't build pytox on arm/windows builds.
